// English AI high-frequency words
export const ENGLISH_AI_WORDS = [
  'utilize', 'utilize', 'utilizes', 'utilized', 'utilizing',
  'delve', 'delves', 'delved', 'delving',
  'tapestry',
  'landscape',
  'comprehensive', 'comprehensively',
  'pivotal',
  'moreover', 'moreovers',
  'furthermore', 'furtherthers',
  'subsequently',
  'in conclusion',
  'additionally',
  'it is worth noting',
  'it is important to',
  'one must acknowledge',
  'robust', 'robustly',
  'seamless', 'seamlessly',
  'cutting-edge',
  'game-changer',
  'revolutionary',
  'streamlined',
  'optimized', 'optimize', 'optimizing', 'optimization',
  'empowered', 'empower', 'empowering',
  'leveraged', 'leverage', 'leveraging',
  'facilitate', 'facilitates', 'facilitated', 'facilitating',
  'endeavor', 'endeavors', 'endeavored', 'endeavoring',
  'innovative', 'innovatively', 'innovation',
  'dynamic', 'dynamically', 'dynamics',
  'versatile', 'versatility',
  'efficient', 'efficiently', 'efficiency',
  'thus', 'thussy',
  'hence', 'henceth',
  'whereas',
  'thereby',
  'accordingly',
  'significantly', 'significance',
  'substantially', 'substantial',
  'considerably', 'considerable',
  'markedly', 'markedly',
  'primarily',
  'essentially',
  'fundamentally', 'fundamental',
  'ultimately',
  'exemplify', 'exemplifies', 'exemplified',
  'paradigm', 'paradigms', 'paradigmatic',
  'sophisticated', 'sophistication',
  'intricate', 'intricately', 'intricacy',
  'prevalent', 'prevalently', 'prevalence',
  'demonstrate', 'demonstrates', 'demonstrated', 'demonstrating',
  'illustrate', 'illustrates', 'illustrated', 'illustrating',
  'manifest', 'manifests', 'manifested', 'manifesting',
  'constitute', 'constitutes', 'constituted', 'constituting',
  'entail', 'entails', 'entailed', 'entailing',
  'pertain', 'pertains', 'pertained', 'pertaining',
  'synthesize', 'synthesizes', 'synthesized', 'synthesizing',
  'elucidate', 'elucidates', 'elucidated', 'elucidating',
  'ameliorate', 'ameliorates', 'ameliorated', 'ameliorating',
  'mitigate', 'mitigates', 'mitigated', 'mitigating',
  'amelioration',
  'proliferate', 'proliferates', 'proliferated', 'proliferating',
  'ubiquitous', 'ubiquitously', 'ubiquity',
  'imperative', 'imperatively',
  'paramount',
  'cardinal',
  'salient', 'saliently',
  'noteworthy',
  'conducive', 'conducively',
  'repertoire',
  'catalyst', 'catalysts', 'catalytic',
  'leverage', 'leverages', 'leveraging',
];

// Chinese AI high-frequency patterns
export const CHINESE_AI_PATTERNS = [
  '综上所述',
  '总而言之',
  '简而言之',
  '一言以蔽之',
  '首先',
  '其次',
  '最后',
  '第一',
  '第二',
  '第三',
  '第四',
  '第五',
  '不仅...而且',
  '不仅...也',
  '既...又',
  '然而',
  '因此',
  '所以',
  '由此可见',
  '总之',
  '值得注意的是',
  '需要指出的是',
  '必须承认',
  '深度',
  '全面',
  '系统',
  '完善',
  '显著',
  '在当今社会',
  '随着社会的发展',
  '随着经济的不断发展',
  '随着科技的不断进步',
  '在这个时代',
  '从根本上',
  '从长远来看',
  '不言而喻',
  '众所周知',
  '不可否认的是',
  '事实上',
  '实际上',
  '从实际出发',
  '具有重要意义',
  '发挥重要作用',
  '起到关键作用',
  '取得显著成效',
  '呈现出良好的发展态势',
  '百花齐放',
  '百家争鸣',
  '与时俱进',
  '开拓创新',
  '砥砺前行',
  '奋勇争先',
  '实现跨越式发展',
  '促进社会和谐',
  '推动社会进步',
  '提高效率',
  '降低成本',
  '增加收益',
  '实现目标',
  '解决问题',
  '应对挑战',
  '抓住机遇',
  '迎接挑战',
  '面对困难',
  '克服困难',
  '战胜困难',
  '取得成功',
  '获得成功',
  '迈向成功',
  '走向成功',
  '开创未来',
  '展望未来',
  '展望未来',
  '在新时代',
  '在新形势下',
  '在新的历史条件下',
  '历史告诉我们',
  '实践证明',
  '实践表明',
  '大量研究表明',
  '研究显示',
  '数据显示',
  '调查表明',
  '统计分析',
  '系统分析',
  '深入分析',
  '全面分析',
  '综合分析',
  '科学依据',
  '理论依据',
  '实践依据',
  '经验总结',
  '教训反思',
  '深入探讨',
  '广泛探讨',
  '全面探讨',
  '系统探讨',
  '深刻阐述',
  '全面阐述',
  '详细阐述',
  '系统阐述',
  '深入浅出',
  '浅显易懂',
  '不言自明',
  '引以为戒',
  '值得深思',
  '发人深省',
];

// AI template patterns (regex)
export const AI_TEMPLATES = [
  // English templates
  /\bIt is (worth noting|important to|generally believed|widely accepted|evident that)\b/gi,
  /\bThis (essay|paper|study|research|article|investigation) (aims to|seeks to|intends to|endeavors to)\b/gi,
  /\bIn (conclusion|summary|summary|closing),?\s*/gi,
  /\bOn the other hand\b/gi,
  /\bTo sum up\b/gi,
  /\bAll in all\b/gi,
  /\bHaving discussed\b/gi,
  /\bIt should be noted\b/gi,
  /\bIt is clear that\b/gi,
  /\bIt goes without saying\b/gi,
  /\bNeedless to say\b/gi,
  /\bBy and large\b/gi,
  /\bAs a matter of fact\b/gi,
  /\bFor all intents and purposes\b/gi,
  /\bWith this in mind\b/gi,
  /\bThat being said\b/gi,
  /\bIn other words\b/gi,
  /\bTo put it differently\b/gi,
  /\bIn fact\b/gi,
  /\bAs a result\b/gi,
  /\bFor this reason\b/gi,
  /\bIn this regard\b/gi,
  /\bWith respect to\b/gi,
  /\bIn terms of\b/gi,
  /\bWhen it comes to\b/gi,
  /\bAs far as.*is concerned\b/gi,
  /\bThe (main|primary|chief|core|fundamental) (reason|purpose|goal|objective|aim) (is|was)\b/gi,
  /\bIt is (well|generally|widely) (known|acknowledged|accepted|recognized)\s+that\b/gi,
  /\bThere is (no|little) (doubt|question)\s+that\b/gi,
  /\bOne of the (most|least) (important|significant|notable) (aspects|factors|elements|considerations)\b/gi,
  /\b(A large number of|A majority of|A significant number of) (studies|researchers|experts|scholars)\s+(have|has)\s+(shown|demonstrated|indicated|suggested|proven)\b/gi,
  // Chinese templates
  /综上所述/gi,
  /总而言之/gi,
  /简而言之/gi,
  /一言以蔽之/gi,
  /一方面.*另一方面/gi,
  /因此/gi,
  /所以/gi,
  /由此可见/gi,
  /总之/gi,
  /值得注意的是/gi,
  /需要指出的是/gi,
  /必须承认/gi,
  /事实上/gi,
  /实际上/gi,
  /一般来说/gi,
  /通常情况下/gi,
  /众所周知/gi,
  /不可否认/gi,
  /毫无疑问/gi,
];

// AI structural patterns (uniform sentence length, etc.)
export const AI_STRUCTURAL_PATTERNS = [
  // Uniform sentence starters
  /\b(Firstly|Secondly|Thirdly|Fourthly|Fifthly)\b.*\b(Firstly|Secondly|Thirdly|Fourthly|Fifthly)\b/gi,
  /\b(In conclusion|To conclude|In summary|In sum)\b.*\b(In conclusion|To conclude|In summary|In sum)\b/gi,
  // Repeating transitions
  /\b(Moreover|Furthermore|Additionally|Also)\b.*\b(Moreover|Furthermore|Additionally|Also)\b/gi,
  // Template openings
  /\bIt is.*that\b.*\bIt is.*that\b/gi,
  /\bThe.*is.*The.*is\b/gi,
];

// Helper function to check multi-line Chinese patterns
export function hasChinesePattern(text: string, start: string, end: string): boolean {
  const startIndex = text.indexOf(start);
  if (startIndex === -1) return false;
  const remaining = text.slice(startIndex + start.length);
  const endIndex = remaining.indexOf(end);
  return endIndex !== -1;
}
